services:
  - type: web
    name: it-solutions-frontend
    env: static
    buildCommand: npm install && npm install @tailwindcss/postcss@4.0.12 --save-dev && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18.x
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 